name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg

      - name: Push snake.svg to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: false
