name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is crucial: grants write permissions to the token

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push pacman-contribution-graph.svg to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Explicitly use the token
          branch: output
          folder: dist
          clean: false
